# Generated by Django 5.1 on 2024-08-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0002_exchangerate_delete_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, verbose_name="Дата и время получения курса"
            ),
        ),
    ]
